return {
    description = "Packages installed via dcli install or dcli search commands",
    packages = {
        "vdpauinfo",
        "libva-utils",
        "cpupower",
        "power-profiles-daemon",
        "ryzenadj",
        "ryzen_smu-dkms-git",
        "obsidian",
        "syncthing",
        "qbittorrent",
        "onlyoffice-bin",
        "flameshot",
        "noctalia-shell",
        "bottles",
        "lutris",
        "rmpc",
        "mpd",
        "mpc",
        "wl-clipboard",
        "cliphist",
        "bat",
        "zram-generator",
        "godot",
        "telegram-desktop",
        "hyprpicker",
        "mpv",
        "ab-download-manager-bin",
        "unrar",
        "xorg-xkill",
        "gocryptfs",
        "nodejs",
        "yt-dlp",
        "gparted",
        "surge-bin",
    },
}
