

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$


# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

windowrule { 
  name = "Ignore maximize requests from apps. You'll probably like this"
  match:class = .*
  suppress_event = maximize
} 

windowrule { 
  name = Fix some dragging issues with XWayland
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
  no_focus = 1
}

windowrule {
  name = Picture in Picture
  match:title = Picture-in-Picture
  pin = 1
  float = 1
  center = 1
  size = 500 300
  move = 10 70
}

windowrule {
  name = Picture in Picture helium
  match:title = Picture in picture
  pin = 1
  float = 1
  center = 1
  size = 500 300
  move = 10 70
}

windowrule {
  name = Flameahot save screenshot
  match:title = Save screenshot
  float = 1
  center = 1
  size = 1000 800
  move = 10 70
}



windowrule {
  name = flameshot
  match:class = flameshot
  match:title = flameshot
  no_anim = 1
  decorate = 0
  float = 1
  pin = 1
  move = 0 0
  fullscreen = 1
  # animation = quick
  # border = 1
}

layerrule {
  name = flameshot
  match:namespace = flameshot
  no_anim = 1
  animation = 0
}



layerrule {
  name = blur logout
  match:namespace = logout_dialog
  blur = 1
}


layerrule {
  name = blur waybar
  match:namespace = waybar
  blur = 1
}

windowrule {
  name = tauba
  match:class = tauba
  pin = 1
  float = 0
  size = "100%" 50
  move = 0 0
  # no_border = true 
}


windowrule {
  name = file-roller
  match:class = org.gnome.FileRoller
  float = 1
  size = "50%" 350
  center = true
  # no_border = true 
}



# Tauri bar
# windowrulev2 = float, class:^(tauri)$
# windowrulev2 = pin, class:^(tauri)$
# windowrulev2 = noborder, class:^(tauri)$
# windowrulev2 = nofocus, class:^(tauri)$



# layerrule = blur,waybar
# blurls = waybar
# windowrule = blur 10,class:kitty
# blurls = logout_dialog
# blurls = kitty