color0 #14130e
color1 #ffb4ab
color2 #d7c950
color3 #cec7a3
color4 #a6d0b8
color5 #d7c950
color6 #cec7a3
color7 #e7e2d9
color8 #959181
color9 #ffb4ab
color10 #d7c950
color11 #cec7a3
color12 #a6d0b8
color13 #d7c950
color14 #cec7a3
color15 #e7e2d9

cursor                #e7e2d9
cursor_text_color     #14130e
background            #14130e
foreground            #e7e2d9
selection_foreground  #cbc6b5
selection_background  #49473a
active_border_color   #d7c950
inactive_border_color #49473a
url_color             #d7c950
