cursor #dfe4dc
cursor_text_color #c1c9bf

foreground            #dfe4dc
background            #101510
selection_foreground  #223526
selection_background  #b6ccb8
url_color             #97d5a5

color0   #101510
color1   #f4926e
color2   #6ad56a
color3   #fff072
color4   #83ca93
color5   #2d6239
color6   #97d5a5
color7   #d2dfd5
color8   #808a82
color9   #ffb89f
color10  #a5ffa6
color11  #fff5a5
color12  #b0eabd
color13  #cbffd6
color14  #ddffe5
color15  #f8fffa
